#!/bin/sh
#read commit message
commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

conventional_regex="^(feat|fix|style|chore|docs|refactor|test)(\(.+\))?: .+$"
if ! echo "$commit_msg" | grep -Eq "$conventional_regex"; then
        echo "Error: The starting of the commit msg must follow the Conventional Commits standard."
        echo "feat     - new feature"
        echo "fix      - bug fixed"
        echo "refactor - refactoring"
        echo "style    - change style(indent, add ';' or something)"
        echo "docs     - document(.txt or some else)"
        echo "test     - test or refectory test code"
        echo "chore    - change etc. (build script or some else)"
        echo "Example  - feat: add new login functionality"
        exit 1
fi

echo "Commit message follows the convention!"
